export const environment = {
  production: false,
  BPF: 'http://travbpf.dev.com/bpf/',
  QUARTZ: 'http://travbpf.dev.com/quartz/',
  systemMaster: 'http://travbpf.dev.com/system-master/',
  hrurl: 'http://travbpf.dev.com/hr/',
  url: 'http://travbpf.dev.com:84/TravelApi/apis',
  JDBCAPI: 'http://travbpf.dev.com/jdbcapi/',
  LOGINAPP: 'http://travsr.dev.com/pages/login',
  PAXDATA: 'http://travbpf.dev.com/paxdata/',
  USERMANAGEMENT: 'http://travbpf.dev.com/usermanagement/',
  AGENT: 'http://travbpf.dev.com/agent/',
  DEALS: 'http://travbpf.dev.com/deals/',
  ResourcesAssignment: 'http://travbpf.dev.com/resources-assignment/',
  SERVICEREQUEST: 'http://travbpf.dev.com/servicerequest/',
  SERVICE_CONFIG: 'http://travbpf.dev.com/travrconfig/',
  E_SERVICE_DYNAMIC_HOST: 'https://travbpf.dev.com',
};
