import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'Team',
    icon: 'icon-users',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/team/team-list',
        title: 'Create Team',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      /* {
        path: '/dashboard/team/addmembers-to-team',
        title: 'Addmembers -Team',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      }, */
      {
        path: '/dashboard/team/tl-to-team',
        title: 'TL-To-Team',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [
          /* {
            path: '/dashboard/team/team-list',
            title: 'Team List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          }, */
          {
            path: '/dashboard/team/addmembers-to-team-list',
            title: 'Team Members List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/team/tl-to-team-list',
            title: 'TL To Team List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    path: '',
    title: 'BPF',
    icon: 'ft-thumbs-up',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/business-process-flow/service-register',
        title: 'Service Register',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/business-process-flow/mail-template',
        title: 'Mail Template',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/business-process-flow/business-process-configurator',
        title: 'BPF',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [
          {
            path: '/dashboard/business-process-flow/service-register-list',
            title: 'Service Register List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/business-process-flow/mail-template-list',
            title: 'Mail Template List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/business-process-flow/business-process-configurator-list',
            title: 'BPF List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    path: '',
    title: 'App Setup',
    icon: 'ft-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/app-setup/module',
        title: 'Module',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/app-setup/sub-module',
        title: 'Sub Module',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/app-setup/status',
        title: 'Status',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/app-setup/default-status',
        title: 'Default Status',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/app-setup/transitions',
        title: 'Transitions',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [
          {
            path: '/dashboard/app-setup/module-list',
            title: 'Module List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/app-setup/sub-module-list',
            title: 'Sub Module List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/app-setup/status-list',
            title: 'Status List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/app-setup/default-status-list',
            title: 'Default Status List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/app-setup/transitions-list',
            title: 'Transitions List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
        ],
      },
    ],
  },

  {
    path: '',
    title: 'Assignment',
    icon: 'icon-user',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/assignment/resources-assignment',
        title: 'Resources Assignment',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [
          {
            path: '/dashboard/assignment/resources-assignment-list',
            title: 'R-Assignment List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
        ],
      },
    ],
  },
  /* {
    path: '',
    title: 'Account Setup',
    icon: 'ft-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/account-setup/role',
        title: 'Create Role',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/account-setup/user-role-mapping',
        title: 'User Role Mapping',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/account-setup/permissions',
        title: 'Permissions',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/account-setup/role-permissions-mapping',
        title: 'Role Permissions Mapping',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/account-setup/register',
        title: 'Register',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [
          {
            path: '/dashboard/account-setup/role-list',
            title: 'Role List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/account-setup/user-role-mapping-list',
            title: 'URM List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/account-setup/permissions-list',
            title: 'Permissions List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/account-setup/role-permissions-mapping-list',
            title: 'RPM List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: '/dashboard/account-setup/register-list',
            title: 'Register List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          }
        ],
      }
    ],
  }, */
  {
    path: '',
    title: 'Service-Config',
    icon: 'icon-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    /*  permissionKey: PERMISSION_KEYS.MENU_HEADER.SERVICECONFIG, */
    submenu: [
      /*   {
        path: '/dashboard/services/service-register',
        title: 'SR API Register',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
          permissionKey: PERMISSION_KEYS.APIREISTER.APIREGISTER_FORM_CREATE,
        submenu: [],
      }, */
      {
        path: '/dashboard/services/field-name',
        title: 'Define SR Fields',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /*   permissionKey: PERMISSION_KEYS.DEFINESRFIELD.DEFINESRFIELD_FORM_CREATE, */
        submenu: [],
      },
      {
        path: '/dashboard/services/service-type',
        title: 'SR Type Create',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /* permissionKey: PERMISSION_KEYS.SR_TYPE.SR_TYPE_FORM_CREATE, */
        submenu: [],
      },
      {
        path: '/dashboard/services/service-menu-type',
        title: 'SR Menu Type Create',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /*  permissionKey: PERMISSION_KEYS.SR_MENU_TYPE.SR_MENU_TYPE_FORM_CREATE, */
        submenu: [],
      },
      {
        path: '/dashboard/services/service-type-group',
        title: 'Create STG',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /*   permissionKey: PERMISSION_KEYS.SERVICE_TYPE_GROUP.SERVICE_TYPE_GROUP_FORM_CREATE, */
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /*   permissionKey: PERMISSION_KEYS.MENU_HEADER.SERVICECONFIG_LIST, */
        submenu: [
          /*   {
            path: '/dashboard/services/service-register-list',
            title: 'SR API List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
             permissionKey: PERMISSION_KEYS.APIREISTER.APIREGISTER_LIST,
            submenu: [],
          }, */
          {
            path: '/dashboard/services/field-name-list',
            title: 'Field List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            /*  permissionKey: PERMISSION_KEYS.DEFINESRFIELD.DEFINESRFIELD_LIST, */
            submenu: [],
          },
          {
            path: '/dashboard/services/service-type-list',
            title: 'SR Types List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            /*   permissionKey: PERMISSION_KEYS.SR_TYPE.SR_TYPE_LIST, */
            submenu: [],
          },
          {
            path: '/dashboard/services/service-menu-type-list',
            title: 'SR Menu Types List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            /* permissionKey: PERMISSION_KEYS.SR_MENU_TYPE.SR_MENU_TYPE_LIST, */
            submenu: [],
          },
          {
            path: '/dashboard/services/service-type-group-list',
            title: 'STG List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            /*  permissionKey: PERMISSION_KEYS.SERVICE_TYPE_GROUP.SERVICE_TYPE_GROUP_LIST, */
            submenu: [],
          },
        ],
      },
    ],
  },

  {
    path: '',
    title: 'Quartz',
    icon: 'icon-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    /*  permissionKey: PERMISSION_KEYS.MENU_HEADER.SERVICECONFIG, */
    submenu: [
      {
        path: '/dashboard/cron-quartz/cron-expression',
        title: 'Quartz Jobs',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /*   permissionKey: PERMISSION_KEYS.APIREISTER.APIREGISTER_FORM_CREATE, */
        submenu: [],
      },
      {
        path: '',
        title: 'List',
        icon: 'icon-grid',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        /*   permissionKey: PERMISSION_KEYS.MENU_HEADER.SERVICECONFIG_LIST, */
        submenu: [
          {
            path: '/dashboard/cron-quartz/cron-expression-list',
            title: 'Quartz List',
            icon: 'ft-arrow-right submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            /*  permissionKey: PERMISSION_KEYS.APIREISTER.APIREGISTER_LIST, */
            submenu: [],
          },
        ],
      },
    ],
  },
];
